### PR TITLE
Created Backed Api

### PR DESCRIPTION
**Pull request by richie1988**
### Project requirements

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).
- Create a new React app called 'hello-react-front-end'
- Initialize your project with Git.
- Create the App component with react-router.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- Display the random greeting in your Greeting component.

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @richie1988, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a link to the frontend part in your README file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rloterh** [comment]
Hi @richie1988 

Can you improve upon this aspects of your ReadMe ASAP?
- Key Features should not be empty
- Can you kindly confirm the title of your project once more?

image

**Review by rloterh — COMMENTED** [review]
Hi Richard, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- Let's ensure the frontend ReadMe contains the link to backend project.
- Let's ensure that all headers have appropriate content below describing them. The _Key Features_ section of your ReadMe should highlight the main features of your project. Let's improve upon this for both the backend and frontend ReadMes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by richie1988** [comment]
### WHY YOU GUYS CANT BETTER CHECK THE README YOU ARE NOT EVEN GOING THROUGH FILES WHICH PART OF README YOU GUYS ARE CHECKING
ShareX_Qiptsyux3O

**Comment by richie1988** [comment]
### THIS IS THE FROND END EXAMPLE TO MY README
ShareX_OVXYMWOsgK

**Comment by prolajumokeoni** [comment]
Hi @richie1988 Good job linking repositories in your readme, Kindly create a pull request in your [frontend repository](https://github.com/richie1988/Hello_react_rails/tree/hello-react-rails?tab=readme-ov-file#---hello_react_rails_backend) so I can proceed with the review, please this is a comment not a review 👍🏿

**Comment by richie1988** [comment]
Alright i will do it now

**Comment by prolajumokeoni** [comment]
Hi @richie1988, I just went through your frontend repository and it seems you submitted the wrong frontend repository, you were meant to create a simple react app but I see your frontend repository has both rails and react setup, kindly check the requirements again,  please this is a comment not a review 👍🏿

**Comment by richie1988** [comment]
Which code did you check its There is no react in the repo Cause this is the code you are reviwieng https://github.com/richie1988/Hello_Rails_backend.git

**Comment by prolajumokeoni** [comment]
Can you come online on slack so I show you? Your [ frontend repository](https://github.com/richie1988/Hello_react_rails/) is not correct, you have both react and rails setup,  you were meant to create a simple react app

**Comment by richie1988** [comment]
Alright

**Comment by prolajumokeoni** [comment]
Hi @richie1988 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the correct link to your frontend repository 👍🏿 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by richie1988** [comment]
chrome_s9Js2mn1st

**Review by Efiamotu-1 — CHANGES_REQUESTED** [review]
Hi @richie1988, 

 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

- [ ] The required changes have been mentioned in the frontend pull request

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@Efiamotu-1](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [@EFYAMOTU](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[Habeeb Efiamotu Musa](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [Habeeb Efiamotu Musa](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mckent05 — APPROVED** [review]
Hi @richie1988, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
approved


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good job creating the backend part of your project 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
